### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by all4fun** [niceit/tabby-cloud-sync-settings#53]
tabby version:   1.0.215
os version:         macOS 14.6.1 (23G93)

install cloud-setting-sync plugin, error:

cloud-setting-sync 中的错误:
[object Object]

**Comment by all4fun** [comment]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/1be9202d-e0d1-4401-90af-f7726b085c1c">

thx

**Comment by all4fun** [comment]
ERROR Error: Uncaught (in promise): Object: {"code":"ETARGET","name":"terminus-cloud-settings-sync","type":"version","wanted":"1.6.5","versions":["1.4.2","1.4.1","1.4.0","1.3.0","1.2.21","1.2.2","1.2.1","1.2.0","1.1.3","1.1.2","1.1.1","1.1.0","1.0.6","1.0.5","1.0.4"],"distTags":{"latest":"1.4.2"},"defaultTag":"latest","message":"No matching version found for terminus-cloud-settings-sync@1.6.5.","stack":"terminus-cloud-settings-sync: No matching version found for terminus-cloud-settings-sync@1.6.5.\n    at pickManifest (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)\n    at /Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18\n    at tryCatcher (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate (node:internal/timers:478:21)","level":"error"}
terminus-cloud-settings-sync: No matching version found for terminus-cloud-settings-sync@1.6.5.
    at pickManifest (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
    at /Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18
    at tryCatcher (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Applications/Tabby.app/Contents/Resources/app.asar/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (node:internal/timers:478:21)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at rejected (/Applications/Tabby.app/Contents/Resources/builtin-plugins/tabby-plugin-manager/dist/index.js:5138:9)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
